kind: Secret
apiVersion: v1
metadata:
  labels:
    {{- include "mayan-edms.labels" . | nindent 4 }}
  name: {{ template "mayan-edms.fullname" . }}-env
type: Opaque
data:
  MAYAN_CELERY_BROKER_URL: {{ include "mayan-edms.env.celery-broker-url" . | b64enc | quote }}
  MAYAN_CELERY_RESULT_BACKEND: {{ include "mayan-edms.env.celery-result-backend" . | b64enc | quote }}
  MAYAN_DATABASES: {{ include "mayan-edms.env.databases" . | b64enc | quote }}
  MAYAN_LOCK_MANAGER_BACKEND_ARGUMENTS: {{ include "mayan-edms.env.lock-manager-backend-arguments" . | b64enc | quote }}
{{- if .Values.objectstorage.enabled }}
  MAYAN_DOCUMENTS_FILE_STORAGE_BACKEND_ARGUMENTS: {{ include "mayan-edms.env.storage-backend-args" . | b64enc | quote }}
{{- end }}
