apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mayan-edms.fullname" . }}
  labels:
    {{- include "mayan-edms.labels" . | nindent 4 }}
spec:
  serviceName: {{ template "mayan-edms.name" . }}
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "mayan-edms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mayan-edms.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mayan-edms.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}:{{ default .Chart.AppVersion .Values.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: MAYAN_SKIP_CHOWN_ON_STARTUP
              value: '1'
            - name: MAYAN_PIP_INSTALLS
              value: {{ include "mayan-edms.env.pip-installs" . | quote }}
          {{- if .Values.tuning.gunicornWorkers }}
            - name: MAYAN_GUNICORN_WORKERS
              value: {{ .Values.tuning.gunicornWorkers | quote }}
          {{- end }}
          {{- if .Values.tuning.gunicornMaxRequests }}
            - name: MAYAN_GUNICORN_MAX_REQUESTS
              value: {{ .Values.tuning.gunicornMaxRequests | quote }}
          {{- end }}
          {{- if .Values.tuning.gunicornMaxRequestsJitters }}
            - name: MAYAN_GUNICORN_MAX_REQUESTS_JITTERS
              value: {{ .Values.tuning.gunicornMaxRequestsJitters | quote }}
          {{- end }}
          {{- if .Values.tuning.gunicornWorkerClass }}
            - name: MAYAN_GUNICORN_WORKER_CLASS
              value: {{ .Values.tuning.gunicornWorkerClass | quote }}
          {{- end }}
          {{- if .Values.tuning.fastQueueWorkers }}
            - name: MAYAN_WORKER_FAST_CONCURRENCY
              value: {{ .Values.tuning.fastQueueWorkers | quote }}
          {{- end }}
          {{- if .Values.tuning.mediumQueueWorkers }}
            - name: MAYAN_WORKER_MEDIUM_CONCURRENCY
              value: {{ .Values.tuning.mediumQueueWorkers | quote }}
          {{- end }}
          {{- if .Values.tuning.slowQueueWorkers }}
            - name: MAYAN_WORKER_SLOW_CONCURRENCY
              value: {{ .Values.tuning.slowQueueWorkers | quote }}
          {{- end }}
          {{- if .Values.objectstorage.enabled }}
            - name: MAYAN_DOCUMENTS_STORAGE_BACKEND
              value: storages.backends.s3boto3.S3Boto3Storage
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "mayan-edms.fullname" . }}-env
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
        {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion }}
          startupProbe:
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            httpGet:
              path: /authentication/logout/
              port: http
        {{- end }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: /authentication/logout/
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: /authentication/logout/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ template "mayan-edms.name" . }}-media
              mountPath: /var/lib/mayan
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
    {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: {{ template "mayan-edms.name" . }}-media
      spec:
      {{- if .Values.persistence.existingClaim }}
        selector:
          matchLabels:
            app: {{ template "mayan-edms.name" . }}
      {{- else }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}
        {{- end }}
        accessModes: [ "{{ .Values.persistence.accessMode }}" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
      {{- end }}
    {{- else }}
      - name: {{ template "mayan-edms.name" . }}-media
        emptyDir: {}
    {{- end }}
